import Product from "./Product";

function ProductContainer() {
    
  return (
    <section id="productContainer">
      <h2>What we reccommend</h2>
      <div className="products fd-row fw-wrap">
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
        <Product
          url="https://placekitten.com/350/350"
          name="Product"
          price={0.00005}></Product>
      </div>
    </section>
  );
}

export default ProductContainer;
